---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: my-nginx
  namespace: asd
  labels:
    app: my-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-nginx
  template:
    metadata:
      labels:
        app: my-nginx
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: my-nginx
                    operator: In
                    values:
                      - "true"
      containers:
        - name: my-nginx
          image: nginx
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: my-nginx
  namespace: asd
spec:
  type: NodePort
  selector:
    app: my-nginx
  ports:
    - port: 80
      nodePort: 30008
#####################################################################################################################
#####################################################################################################################
#####################################################################################################################
