global:
  scrape_interval: 10s

scrape_configs:
  - job_name: kafka-1
    static_configs:
      - targets: ['kafka-1:7071']

  - job_name: kafka-2
    static_configs:
      - targets: ['kafka-2:7071']

  - job_name: kafka-3
    static_configs:
      - targets: ['kafka-3:7071']

  - job_name: kafka-4
    static_configs:
      - targets: ['kafka-4:7071']

  - job_name: kafka
    static_configs:
      - targets: ['kafka-1:7071', 'kafka-2:7071', 'kafka-3:7071', 'kafka-4:7071']

  - job_name: kafka-exporter
    static_configs:
      - targets: ['kafka-exporter:9308']

