version: "3.3"
services:

  zookeeper-1:
    image: confluentinc/cp-zookeeper:5.2.2
    volumes:
      - "./volumes/zookeeper-1/data:/var/lib/zookeeper/data"
      - "./volumes/zookeeper-1/log:/var/lib/zookeeper/log"
    environment:
      ZOOKEEPER_SERVER_ID: "1"
      ZOOKEEPER_CLIENT_PORT: "2181"
      ZOOKEEPER_TICK_TIME: "2000"
      ZOOKEEPER_INIT_LIMIT: "5"
      ZOOKEEPER_SYNC_LIMIT: "2"
      ZOOKEEPER_SERVERS: "zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888"

  zookeeper-2:
    image: confluentinc/cp-zookeeper:5.2.2
    volumes:
      - "./volumes/zookeeper-2/data:/var/lib/zookeeper/data"
      - "./volumes/zookeeper-2/log:/var/lib/zookeeper/log"
    environment:
      ZOOKEEPER_SERVER_ID: "2"
      ZOOKEEPER_CLIENT_PORT: "2181"
      ZOOKEEPER_TICK_TIME: "2000"
      ZOOKEEPER_INIT_LIMIT: "5"
      ZOOKEEPER_SYNC_LIMIT: "2"
      ZOOKEEPER_SERVERS: "zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888"

  zookeeper-3:
    image: confluentinc/cp-zookeeper:5.2.2
    volumes:
      - "./volumes/zookeeper-3/data:/var/lib/zookeeper/data"
      - "./volumes/zookeeper-3/log:/var/lib/zookeeper/log"
    environment:
      ZOOKEEPER_SERVER_ID: "3"
      ZOOKEEPER_CLIENT_PORT: "2181"
      ZOOKEEPER_TICK_TIME: "2000"
      ZOOKEEPER_INIT_LIMIT: "5"
      ZOOKEEPER_SYNC_LIMIT: "2"
      ZOOKEEPER_SERVERS: "zookeeper-1:2888:3888;zookeeper-2:2888:3888;zookeeper-3:2888:3888"

  zoo-navigator-api:
    image: elkozmon/zoonavigator-api:0.6.0
    environment:
      API_HTTP_PORT: "9082"

  zoo-navigator-web:
    image: elkozmon/zoonavigator-web:0.6.0
    ports:
      - "9001:9001"
    environment:
      WEB_HTTP_PORT: "9001"
      API_HOST: "zoo-navigator-api"
      API_PORT: "9082"
      AUTO_CONNECT_CONNECTION_STRING: "zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181"
    depends_on:
      - zoo-navigator-api
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3

  utools:
    image: utools:0.0.1

  kafka-1:
    image: wurstmeister/kafka:2.12-2.2.1
    volumes:
      - "./volumes/kafka-1:/kafka"
      - "./configs:/configs"
    ports:
      - "9091:9091"
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: "1"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-1:9091"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9091"
      KAFKA_AUTO_CREATE_TOPICS_ENABLED: "true"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181"
      KAFKA_DEFAULT_REPLICATION_FACTOR: "2"
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      #KAFKA_HEAP_OPTS: "-Xmx720M -Xms720M"
      KAFKA_OPTS: "-javaagent:/configs/kafka/jmx_prometheus_javaagent.jar=7071:/configs/kafka/prom-jmx-agent-config.yml"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "2"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "15000"
      KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS: "1000"
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: "30000"

  kafka-2:
    image: wurstmeister/kafka:2.12-2.2.1
    volumes:
      - "./volumes/kafka-2:/kafka"
      - "./configs:/configs"
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: "2"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-2:9092"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092"
      KAFKA_AUTO_CREATE_TOPICS_ENABLED: "true"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181"
      KAFKA_DEFAULT_REPLICATION_FACTOR: "2"
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      #KAFKA_HEAP_OPTS: "-Xmx720M -Xms720M"
      KAFKA_OPTS: "-javaagent:/configs/kafka/jmx_prometheus_javaagent.jar=7071:/configs/kafka/prom-jmx-agent-config.yml"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "2"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "15000"
      KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS: "1000"
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: "30000"

  kafka-3:
    image: wurstmeister/kafka:2.12-2.2.1
    volumes:
      - "./volumes/kafka-3:/kafka"
      - "./configs:/configs"
    ports:
      - "9093:9093"
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: "3"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-3:9093"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9093"
      KAFKA_AUTO_CREATE_TOPICS_ENABLED: "true"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181"
      KAFKA_DEFAULT_REPLICATION_FACTOR: "2"
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      #KAFKA_HEAP_OPTS: "-Xmx720M -Xms720M"
      KAFKA_OPTS: "-javaagent:/configs/kafka/jmx_prometheus_javaagent.jar=7071:/configs/kafka/prom-jmx-agent-config.yml"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "2"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "15000"
      KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS: "1000"
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: "30000"

  kafka-4:
    image: wurstmeister/kafka:2.12-2.2.1
    volumes:
      - "./volumes/kafka-4:/kafka"
      - "./configs:/configs"
    ports:
      - "9094:9094"
    depends_on:
      - zookeeper-1
      - zookeeper-2
      - zookeeper-3
    environment:
      KAFKA_BROKER_ID: "4"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://kafka-4:9094"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9094"
      KAFKA_AUTO_CREATE_TOPICS_ENABLED: "true"
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper-1:2181,zookeeper-2:2181,zookeeper-3:2181"
      KAFKA_DEFAULT_REPLICATION_FACTOR: "2"
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      #KAFKA_HEAP_OPTS: "-Xmx720M -Xms720M"
      KAFKA_OPTS: "-javaagent:/configs/kafka/jmx_prometheus_javaagent.jar=7071:/configs/kafka/prom-jmx-agent-config.yml"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "2"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "15000"
      KAFKA_GROUP_MIN_SESSION_TIMEOUT_MS: "1000"
      KAFKA_GROUP_MAX_SESSION_TIMEOUT_MS: "30000"

  kafka-manager:
    image: sheepkiller/kafka-manager
    ports:
      - 9077:9000
    environment:
      ZK_HOSTS: "zookeeper-1:2181,zookeeper-2:2182,zookeeper-3:2183"
      APPLICATION_SECRET: "letmein"

  prometheus:
    image: prom/prometheus:v2.10.0
    volumes:
      - "./volumes/prometheus:/prometheus"
      - "./configs/etc_prometheus:/etc/prometheus"

  kafka-exporter:
    image: danielqsj/kafka-exporter
    command:
      - "--kafka.server=kafka-1:9091"
      - "--kafka.server=kafka-2:9092"
      - "--kafka.server=kafka-3:9093"
      - "--kafka.server=kafka-4:9094"

  grafana:
    image: grafana/grafana:5.4.3
    ports:
      - "3000:3000"
    volumes:
      - "./grafana_volume:/var/lib/grafana"
    user: root
