---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-1
  labels:
    app: kafka-1
spec:
  serviceName: kafka-1
  replicas: 1
  selector:
    matchLabels:
      app: kafka-1
  template:
    metadata:
      labels:
        app: kafka-1
    spec:
      containers:
        - name: kafka-1
          image: wurstmeister/kafka:2.12-2.2.1
          imagePullPolicy: Never
          ports:
            - containerPort: 2181
          volumeMounts:
            - mountPath: /kafka
              name: mass-volume-kafka-1-data
          env:
            - name: HOST
              value: "kafka-1-0.kafka-1.default.svc.cluster.local"
            - name: ZOO1
              value: "zookeeper-1-0.zookeeper-1.default.svc.cluster.local"
            - name: ZOO2
              value: "zookeeper-2-0.zookeeper-2.default.svc.cluster.local"
            - name: ZOO3
              value: "zookeeper-3-0.zookeeper-3.default.svc.cluster.local"
            - name: KAFKA_ADVERTISED_LISTENERS
              value: "PLAINTEXT://$(HOST):9092"
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://$(HOST):9092"
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: "$(ZOO1):2181,$(ZOO2):2181,$(ZOO3):2181"
            - name: KAFKA_BROKER_ID
              value: "1" # KAFKA_BROKER_ID
            - name: KAFKA_DEFAULT_REPLICATION_FACTOR
              value: "2"
            - name: KAFKA_LOG4J_LOGGERS
              value: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      volumes:
        - name: mass-volume-kafka-1-data
          persistentVolumeClaim:
            claimName: mass-volume-kafka-1-data
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-1
spec:
  selector:
    app: kafka-1
  ports:
    - port: 9092
      targetPort: 9092
#####################################################################################################################
#####################################################################################################################
#####################################################################################################################
