---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper-1
  labels:
    app: zookeeper-1
spec:
  serviceName: zookeeper-1
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper-1
  template:
    metadata:
      labels:
        app: zookeeper-1
    spec:
      containers:
        - name: zookeeper
          image: confluentinc/cp-zookeeper:5.2.2
          imagePullPolicy: Never
          ports:
            - containerPort: 2181
              protocol: TCP
          volumeMounts:
            - mountPath: /var/lib/zookeeper/data
              name: mass-volume-zoo-1-data
            - mountPath: /var/lib/zookeeper/log
              name: mass-volume-zoo-1-log
          env:
            - name: ZOOKEEPER_SERVER_ID
              value: "1" # ZOOKEEPER_SERVER_ID
            - name: ZOOKEEPER_CLIENT_PORT
              value: "2181"
            - name: ZOOKEEPER_TICK_TIME
              value: "2000"
            - name: ZOOKEEPER_INIT_LIMIT
              value: "5"
            - name: ZOOKEEPER_SYNC_LIMIT
              value: "2"
            - name: ZOO1
              value: "zookeeper-1-0.zookeeper-1.default.svc.cluster.local"
            - name: ZOO2
              value: "zookeeper-2-0.zookeeper-2.default.svc.cluster.local"
            - name: ZOO3
              value: "zookeeper-3-0.zookeeper-3.default.svc.cluster.local"
            - name: ZOOKEEPER_SERVERS
              value: "$(ZOO1):2888:3888;$(ZOO2):2888:3888;$(ZOO3):2888:3888"
      volumes:
        - name: mass-volume-zoo-1-data
          persistentVolumeClaim:
            claimName: mass-volume-zoo-1-data
        - name: mass-volume-zoo-1-log
          persistentVolumeClaim:
            claimName: mass-volume-zoo-1-log
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-1
spec:
  selector:
    app: zookeeper-1
  ports:
    - port: 2181
      targetPort: 2181
#####################################################################################################################
#####################################################################################################################
#####################################################################################################################
